### ISSUE TITLE
Does not work on 1.13

### ISSUE THREAD

**Issue by klugemonkey** [zDevelopers/zLib#17]
NPE on EnchantMentWrapper for GlowEffect constructor.  No longer takes an id, but a string in 1.13 since enchantment ids are deprecated.

**Comment by AmauryCarrade** [comment]
Hi, thank you for your report! Indeed the 1.13 support is not out yet. I'll try to work on that this month. I cannot give you a date sadly (because all of this is on my free time) but it is definitely on my list!

**Comment by danjono** [comment]
I've been trying to convert this for you. I cannot find a good way of registering a custom enchantment now on 1.13 since getByName and getByKey returns null when trying to register it (which you seem to have released I see in a comment on the code)

Just so you can see, I've [made a post](https://www.spigotmc.org/threads/help-creating-custom-enchantments-in-1-13-x.337474/) on Spigot asking for some advice on how to register custom enchantments going forward with 1.13+. I am wondering though if this may be a vanilla bug that needs to be reported to Mojang.

The other way I have thought of doing this since I believe you only use the 'glow' effect as an identifier in ImageOnMap that it's been generated by the plugin is use NBT data instead and set a identify key which can then be read when executing the relevant code again. Not a great solution however if you want to have backwards compatibility if old servers have previous generated maps as they would be useless. It would be fine for fresh servers.

If I found out anything else I'll let you know also.

**Comment by tianji1993** [comment]
@danjono this maybe helpful:
https://www.spigotmc.org/threads/enchantmentwrapper-constructor-arguments-changing-with-versions.329593/

**Comment by ItsTehBrian** [comment]
Any updates on this? Currently would like to update my server to 1.14 however ImageOnMap is pretty important, and zLib is a dependency.

**Comment by AmauryCarrade** [comment]
The latest commit should be pretty functionnal on both 1.13 and 1.14. I'm now finishing ImageOnMap compatibility with 1.13+ (c @ItsTehBrian). Sorry for the delays, I had a long no-Minecraft period and was the only maintainer left…
